/*
 * generated by Xtext 2.15.0
 */
package org.eclipse.xtext.example.arithmetics.ide


/**
 * Use this class to register ide components.
 */
class ArithmeticsIdeModule extends AbstractArithmeticsIdeModule {
}
