/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>From</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.From#getServer <em>Server</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFrom()
 * @model
 * @generated
 */
public interface From extends EObject
{
  /**
   * Returns the value of the '<em><b>Server</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.myDsl.Server}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Server</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Server</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.Server
   * @see #setServer(Server)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getFrom_Server()
   * @model
   * @generated
   */
  Server getServer();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.From#getServer <em>Server</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Server</em>' attribute.
   * @see org.xtext.example.mydsl.myDsl.Server
   * @see #getServer()
   * @generated
   */
  void setServer(Server value);

} // From
